name: GitHub Actions Library
on:
  push:
    branches: [ "github-actions-library" ]
  pull_request:
    branches: [ "github-actions-library" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: GitHub-Actions-Library

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browser
      run: npx playwright install

    - name: Manually change config for tests
      run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js

    - name: Run backend
      run: npm run server &
      
    - name: Run client
      run: npm run start &

    - name: Run tests
      run: npm run test

  deploy_be:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/github-actions-library' && github.event_name == 'push'
    steps:
    - name: Deploy to Render.com
      uses: JorgeLNJunior/render-deploy@v1.4.7
      with:
        service_id: ${{ secrets.LIBRARY_BE_SERVICE_ID }}
        api_key: ${{ secrets.LIBRARY_API_KEY }}
        github_token: ${{ github.token }}
        wait_deploy: true      

  deploy_fe:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/github-actions-library' && github.event_name == 'push'
    steps:
    - name: Deploy to Render.com
      uses: JorgeLNJunior/render-deploy@v1.4.7
      with:
        service_id: ${{ secrets.LIBRARY_FE_SERVICE_ID }}
        api_key: ${{ secrets.LIBRARY_API_KEY }}
        github_token: ${{ github.token }}
        wait_deploy: true      
