name: GitHub Actions Library
on:
  push:
    branches: [ "github-actions-library" ]
  pull_request:
    branches: [ "github-actions-library" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: GitHub-Actions-Library

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browser
      run: npx playwright install

    - name: Run backend
      run: npm run server &
      
    - name: Run client
      run: npm run start &

    - name: Run tests
      run: npm run test
